//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public int idAdmin { get; set; }
        public string documento { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
