//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public string codigo { get; set; }
        public string documentoPaciente { get; set; }
        public Nullable<int> idProcedimiento { get; set; }
        public string fecha { get; set; }
        public string valorTotal { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Procedimientos_realizados Procedimientos_realizados { get; set; }
    }
}
